# Site Settings
title: Amanda Verga's Website
email: amandayverga@gmail.com
description: >
  Amanda's attempt at creating a website.
baseurl: "/amandayverga"
url: "https://amandayverga.github.io/"
github_username:  amandayverga
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
